### ISSUE TITLE
Ability to use old transformer system

### ISSUE THREAD

**Issue by DaMatrix** [cpw/coremods#1]
Hi! As I hear that this is going to be the replacement for the current coremod/transformer system at some point in the foreseeable future, I was wondering if, at any point, this will be made able to load transformers from the old system (even if it's only possible with e.g. a config option that's off by default).  This seems great for mods that only make a few small changes, but for mods that have hundreds of base edits (like [CubicChunks](https://github.com/OpenCubicChunks/CubicChunks/tree/MC_1.12/src/main/java/cubicchunks/asm/mixin)) this seems more of a pain, and would force the [clean, easily readable ASM](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/master/src/main/java/valkyrienwarfare/mixin/world/chunk/MixinChunk.java) code using tools like [Mixin](https://github.com/SpongePowered/Mixin) to be replaced with a [scrambled, nearly incomprehensible mess of opcodes](https://github.com/fr1kin/packetlistener/blob/master/patch/PatchNetManager.java#L39-L51).

If you plan not to allow this, would you mind explaining why not?
Thanks in advance!

**Comment by cpw** [comment]
Mixin is not going away. Mixin will be using a different system. Mixin will be natively supported in the new environment.
